feat(check-extension): add unified gate step to know if successful

diff --git a/.github/workflows/check-extension.yaml b/.github/workflows/check-extension.yaml
--- a/.github/workflows/check-extension.yaml
+++ b/.github/workflows/check-extension.yaml
@@ -307,3 +307,18 @@ jobs:
           name: sandbox-data-${{ fromJSON(steps.magento-version.outputs.version) }}
           path: ${{ steps.setup-magento.outputs.path }}/dev/tests/integration/tmp/sandbox-*
           retention-days: 3
+
+    gate:
+      name: Check Extension Success
+      runs-on: ubuntu-latest
+      needs: [compute_resolved, unit-test-extension, compile-extension, compute_latest_matrix, coding-standard, integration_test]
+      if: always()
+      steps:
+        - name: Check results
+          run: |
+            if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+              echo "One or more jobs failed or were cancelled:"
+              echo '${{ toJSON(needs.*.result) }}'
+              exit 1
+            fi
+            echo "All jobs succeeded or were skipped."
